### ISSUE TITLE
Concerns on the generalization performance of the ensemble after using DVERGE

### ISSUE THREAD

**Issue by xuyxu** [zjysteven/DVERGE#3]
Hi @zjysteven, thanks for this solid and insightful work!

We are kind of interested in the generalization performance after using DVERGE (i.e., classification error on the clean dataset instead of robustness against adversarial samples), and I will appreciate it very much if you could share some results or ideas.

FYI, here is a paper saying that adversatial training also improves the generalization performance: `B. Lakshminarayanan, A. Pritzel, C. Blundell., Simple and Scalable Predictive Uncertainty Estimation using Deep Ensembles, NIPS 2017`. However, our experiment results are not quite satisfactory.

**Comment by zjysteven** [comment]
Hi @xuyxu,

Thanks for your interest in our work. Actually, we are also curious whether DVERGE can benefit clean accuracy but haven't got chance to really try anything. I'll answer your question in two folds.
 
1. Can current DVERGE configuration benefit clean accuracy?
Current DVERGE configuration is dedicated to improving adversarial robustness, and since it is well recognized that clean accuracy and robustness have a trade-off [1], DVERGE (in its current form) can degrade the clean accuracy compared with standard ensembles (as shown by the results in e.g. Table 4 of our paper).

2. Can DVERGE have the potential to benefit clean accuracy?
I have thought about this question once and I think there might be a chance. My thought is based on this paper [2], which provides a feature perspective on why ensembles can provide better generalization (see Sec 1.5). Specifically, they find that due to the "multi-view" structure presented in vision datasets and randomness during the model training, each sub-model can pick up different "features" to accomplish the classification task. When combined together, the ensemble will make the decision based on a more comprehensive set of features so the generalization is better.
Then, if we interpret DVERGE from the above perspective, we can see that DVERGE is more explicitly trying to make each sub-model pick up more diverse features. In this sense, DVERGE has the potential to further boost the generalization compared with naive ensembles due to the diversity induced in the features learned by each sub-model.
Some possible modifications to DVERGE that might give better generalization: Using smaller perturbation budget (the epsilon and number of perturbation steps); Using separate batch-norm for clean and adv examples [3]. Actually [3] can be pretty helpful since it demonstrates how adversarial training can be used to improve generalization.


[1] Tsipras, Dimitris, et al. "Robustness may be at odds with accuracy." arXiv preprint arXiv:1805.12152 (2018).
[2] Allen-Zhu, Zeyuan, and Yuanzhi Li. "Towards Understanding Ensemble, Knowledge Distillation and Self-Distillation in Deep Learning." arXiv preprint arXiv:2012.09816 (2020).
[3] Xie, Cihang, et al. "Adversarial examples improve image recognition." Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2020.

**Comment by xuyxu** [comment]
Thanks for your detailed answer. We will stay tuned for more academic works, good luck!
