### ISSUE TITLE
How to generate adversarial examples for black-block attack ？

### ISSUE THREAD

**Issue by HuangZuShu** [zjysteven/DVERGE#6]
Hi，would you mind providing a script for generating adversarial examples to evaluate  black-block attack？

**Comment by zjysteven** [comment]
Hi, the generation of black-box adversarial examples is almost the same as doing white-box attacks except that 1) we are using surrogate models instead of the target white-box models, and 2) the attack hyperparameters such as the number of iterations might be different (please see our paper for details).

I may not be able to provide the exact script (since this project has been a while ago), but it should be pretty straightforward to generate black-box adversarial examples by adapting [this script](https://github.com/zjysteven/DVERGE/blob/main/eval/eval_wbox.py). Also, note that we already provide the black-box adversarial examples generated ourselves (see [readme](https://github.com/zjysteven/DVERGE/blob/main/README.md) "Date and pre-trained models").
